### ISSUE TITLE
mangos QUIC benchmarks.

### ISSUE THREAD

**Issue by egorsmkv** [iwasaki-kenta/mangos-benchmark#1]
There is an implementation over the QUIC protocol https://github.com/lthibault/quic-mangos
Please, add a benchmark with that protocol and publish results.

**Comment by iwasaki-kenta** [comment]
> There is an implementation over the QUIC protocol https://github.com/lthibault/quic-mangos
> Please, add a benchmark with that protocol and publish results.

It appears to only support mangos v1. Could you add support for mangos v2?

**Comment by egorsmkv** [comment]
> It appears to only support mangos v1. Could you add support for mangos v2?

Where do you see this information? The readme has a url to github.com/nanomsg/mangos, this url stands for mangos v2.

**Comment by iwasaki-kenta** [comment]
> > It appears to only support mangos v1. Could you add support for mangos v2?
> 
> Where do you see this information? The readme has a url to github.com/nanomsg/mangos, this url stands for mangos v2.

Oh, I suppose that the repository depends on the master version of mangos v2 then. The benchmarks here strictly use the v2 dependency from this import: `nanomsg.org/go/mangos/v2`.

**Comment by egorsmkv** [comment]
So, you can use that project to add the QUIC transport in your benchmarks.

**Comment by iwasaki-kenta** [comment]
All internal source code of mangos v2 however uses the import link I specified. It would be best to update the QUIC transport to follow the same conventions.

**Comment by egorsmkv** [comment]
>All internal source code of mangos v2 however uses the import link I specified. It would be best to update the QUIC transport to follow the same conventions.

@iwasaki-kenta I don’t argue. But I’m not the author of that project.
